// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_vaPD6VPhxRS87QvadaqoPJR8rKIqTE',
    appId: '1:331514885962:web:808462aae3bfa674a0f3b3',
    messagingSenderId: '331514885962',
    projectId: 'healthcare-bigproject',
    authDomain: 'healthcare-bigproject.firebaseapp.com',
    storageBucket: 'healthcare-bigproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJ-9wKSBLOm5Y18JTO9SIMcHrwfF-Vr0',
    appId: '1:331514885962:android:49fa332e657be3d0a0f3b3',
    messagingSenderId: '331514885962',
    projectId: 'healthcare-bigproject',
    storageBucket: 'healthcare-bigproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg6Mfr-1eWP8h9bRXZbrOHhlNlkGPPn1g',
    appId: '1:331514885962:ios:9ff8bb9a7aacee4ea0f3b3',
    messagingSenderId: '331514885962',
    projectId: 'healthcare-bigproject',
    storageBucket: 'healthcare-bigproject.appspot.com',
    iosClientId: '331514885962-7qdqkjenq1ioqp966357odcnjjs2r63o.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthcareBigproject',
  );
}
